name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ex00:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "install dependencies"
      run: sudo apt install valgrind -y
    - name: compilation of ex00
      run: make -C ./ex00
    - name: run tests ex00
      run: valgrind --leak-check=full --track-fds=yes ./ex00/easyfind

  ex01:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "install dependencies"
      run: sudo apt install valgrind -y
    - name: compilation of ex01
      run: make -C ./ex01
    - name: run tests ex01
      run: valgrind  --leak-check=full --track-fds=yes --error-exitcode=1 ./ex01/span

  ex02:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "install dependencies"
      run: sudo apt install valgrind -y
    - name: compilation of ex02
      run: make -C ./ex02
    - name: run tests ex02
      run: valgrind  --leak-check=full --track-fds=yes --error-exitcode=1 ./ex02/mutantStack